### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by KARAKANY** [LinuxPhantom/Raven-Storm-DDoS#1]
raven storm crash when i try to run stress test on l4 module

**Comment by KARAKANY** [comment]
error: Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\New folder (3)\Raven-Storm-master\Raven-Storm\CLIF_Framework\framework.py", line 106, in run
    command[1](console_command)
TypeError: Main.l4() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\New folder (3)\Raven-Storm-master\Raven-Storm\CLIF_Framework\framework.py", line 106, in run
    command[1](console_command)
  File "C:\Users\Administrator\Desktop\New folder (3)\Raven-Storm-master\Raven-Storm\modules\l4\main.py", line 621, in run
    execute()
  File "C:\Users\Administrator\Desktop\New folder (3)\Raven-Storm-master\Raven-Storm\modules\l4\main.py", line 523, in execute
    if len(var.target) == 1 and len(var.port) == 1:
TypeError: object of type 'NoneType' has no len()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\New folder (3)\Raven-Storm-master\Raven-Storm\main.py", line 30, in <module>
    run()
  File "C:\Users\Administrator\Desktop\New folder (3)\Raven-Storm-master\Raven-Storm\main.py", line 26, in run
    main_console.run()
  File "C:\Users\Administrator\Desktop\New folder (3)\Raven-Storm-master\Raven-Storm\CLIF_Framework\framework.py", line 108, in run
    command[1]()
  File "C:\Users\Administrator\Desktop\New folder (3)\Raven-Storm-master\Raven-Storm\modules\main.py", line 213, in l4
    var.modules["Layer4"].run()
  File "C:\Users\Administrator\Desktop\New folder (3)\Raven-Storm-master\Raven-Storm\CLIF_Framework\framework.py", line 108, in run
    command[1]()
TypeError: Main.run() missing 1 required positional argument: 'command'

**Comment by KARAKANY** [comment]
missclick
